### ISSUE TITLE
Boruta status

### ISSUE THREAD

**Issue by alejandrodevs** [malach-it/boruta-server#27]
Hi @patatoid 

 I am using Boruta right now in my identity provider server and I realized that the project was deleted from gitlab. Then, I found this repository and I have some questions regarding to status of the project. Is this a continuation of the previous project? Is it a new approach?  Is there some documentation about this change?
 
 Thanks for your contribution and your amazing work.

**Comment by patatoid** [comment]
Hi @alejandrodevs,

Thank you for the interest in my work. 

It is the very same codebase. I had some issues with gitlab then migrated to github.

For now, I am quite overwhelmed with administrative work but hope to be able to work again soon.
