### ISSUE TITLE
Error when connecting via oidcc Elixir library

### ISSUE THREAD

**Issue by Stratus3D** [malach-it/boruta-server#54]
I'm running boruta-server locally for developing an Elixir app that authenticates users via OIDC using the Erlang/Eixir oidcc library. Running a release of this application locally I get an error from oidcc complaining about a missing config property:

```
11:33:48.684 [error] GenServer <redacted>.OpenIdConfigurationProvider terminating
** (stop) {:configuration_load_failed, {:missing_config_property, :scopes_supported}}
Last message: {:continue, :load_configuration}
State: {:state, :undefined, :undefined, "https://<redacted>", %{}, :undefined, :undefined,<redacted>.OpenIdConfigurationProvider, 1000, 30000, :stop, :undefined}
```

I can hack around the error by making the following change to boruta-server:

```diff
diff --git a/apps/boruta_web/lib/boruta_web/views/oauth_view.ex b/apps/boruta_web/lib/boruta_web/views/oauth_view.ex
index efd524e9..281a45e9 100644
--- a/apps/boruta_web/lib/boruta_web/views/oauth_view.ex
+++ b/apps/boruta_web/lib/boruta_web/views/oauth_view.ex
@@ -63,6 +63,7 @@ defmodule BorutaWeb.OauthView do
         "authorization_code",
         "refresh_token"
       ],
+      "scopes_supported" => ["openid"],
       "response_types_supported" => [
         "code",
         "token",
```

Any idea why this change is necessary? I see the`openid` scope listed as public in the boruta web admin:

![Screenshot 2024-06-03 at 15-07-15 Boruta · Administration panel](https://github.com/malach-it/boruta-server/assets/1520926/41d48f26-e18f-4ebb-855b-a7b07d07be0b)

**Comment by patatoid** [comment]
I just added `scopes_supported` claim in openid well-known configuration in https://github.com/malach-it/boruta-server/commit/5dff3957c228eefbb7e436d8b4dc85d76450bdc8

The changes are available on master.

**Comment by Stratus3D** [comment]
Any idea when a new version with the changes will be released?

**Comment by patatoid** [comment]
I will have a look at it, keep you posted (in few days)
