### ISSUE TITLE
Boruta-Server listens on 0.0.0.0 despite the .env.production config file referencing localhost

### ISSUE THREAD

**Issue by dscp46** [malach-it/boruta-server#56]
Dear Maintainer,

When running Boruta-Server, using the system-wide setup and the following `.env.production` config, the server sockets are bound to `0.0.0.0:8180`, `0.0.0.0:8181`, `0.0.0.0:8182` and `0.0.0.0:8183`, despite the configuration explicitly referencing `localhost` as the host.

```
MIX_ENV=prod
SECRET_KEY_BASE=<stripped sensitive data>
POSTGRES_USER=boruta
POSTGRES_PASSWORD=<stripped sensitive data>
POSTGRES_DATABASE=boruta_release
POSTGRES_HOST=localhost
POOL_SIZE=5
MAX_LOG_RETENTION_DAYS=60
BORUTA_ADMIN_OAUTH_CLIENT_ID=5905075e-8c62-4b53-9f19-154b0ef2b0e0
BORUTA_ADMIN_OAUTH_CLIENT_SECRET=<stripped sensitive data>
BORUTA_ADMIN_OAUTH_BASE_URL=https://login.example.com
BORUTA_ADMIN_EMAIL=admin@example.com
BORUTA_ADMIN_PASSWORD=<stripped sensitive data>
BORUTA_ADMIN_HOST=localhost
BORUTA_ADMIN_PORT=8181
BORUTA_ADMIN_BASE_URL=https://adm.login.example.com
BORUTA_OAUTH_HOST=localhost
BORUTA_OAUTH_PORT=8180
BORUTA_OAUTH_BASE_URL=https://login.example.com
BORUTA_GATEWAY_PORT=8182
BORUTA_GATEWAY_SIDECAR_PORT=8183
BORUTA_GATEWAY_CONFIGURATION_PATH=config/example-gateway-configuration.yml
```

On that machine, the /etc/hosts file contains the following lines, refering to localhost, which is the default setup with any recent debian setup:

```
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
```

Additionally, we could note that Boruta-Server chose to bind to `0.0.0.0` instead of `::`, which makes it incompatible with IPv6.
For a reminder, a socket bound on `::` is able to accept requests both from IPv6 and IPv4 clients.

Tested version: `0.3.0`.

Kind regards,

**Comment by patatoid** [comment]
I added the ability to configure the binding of the oauth and admin servers, the gateway one being more experimental, I kept as it is.

The changes are available on master https://github.com/malach-it/boruta-server/commit/e3df716f4bff19755c007be808d62e4e96bb04e2

Keep you posted for a release.
