### ISSUE TITLE
Unable to run release on MacOS

### ISSUE THREAD

**Issue by Stratus3D** [malach-it/boruta-server#57]
When running a boruta-server release on MacOS I get this error:

```
hostname: illegal option -- i
usage: hostname [-f] [-s | -d] [name-of-host]
```

This is due to this line: https://github.com/malach-it/boruta-server/blob/master/rel/env.sh.eex#L20 Apparently the `-i` flag isn't available on MacOS. Happy to create a PR to fix this, but I'm not sure what the best solution would be. A couple things come to mind:

* **Just use `hostname` and use hostname instead of IP**. I imagine there is a reason IP address is used.
* **Conditional logic for operating system**. Use something like `uname` and use hostname on MacOS or use `ifconfig` or `dig` to determine IP on MacOS.

Happy to create a PR if that is desired.

**Comment by patatoid** [comment]
Hi @Stratus3D ,

Thank you for the bug report.

I think the best would be to have an os conditional statement keeping in mind that having the IP in the Erlang node name was a choice taken for the need of further use. Saying that as a suggestion since only the node name format matters.
